# Generated by Django 4.1.1 on 2022-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_authers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='describtion',
            field=models.CharField(default='No Describtion available for this Book!', max_length=255),
        ),
    ]
